version: '3.7'

services:
  mongo:
    image: mongo:6.0.6
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoDev
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    volumes:
      - 'chupito_mongo_data:/data/db'

  # app:
  #   build:
  #     context: BE-CHUPITO/
  #     dockerfile: Dockerfile
  #   image: be-chupito
  #   ports:
  #     - "5002:5002"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGODB_URI=mongodb://mongoDev:Passw0rd@mongo:27017/?authSource=admin

volumes:
  chupito_mongo_data: null
