version: '3.7'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27030:27017'
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoDev
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
