---
name: Check Pull Request

on: [pull_request]  # yamllint disable-line rule:truthy

env:
  NODE_VERSION: '18.16.0'

jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Yaml lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Markdown lint
        uses: docker://markdownlint/markdownlint:latest
        with:
          args: "--warnings ."

  docker_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Docker lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          ignore: DL4006 SC2006

  eslint_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Eslint lint
        id: eslint-test
        run: |
          yarn install
          # npm run lint

  unit_test:
    runs-on: ubuntu-latest
    needs: ['yaml_lint', 'markdown_lint', 'docker_lint', 'eslint_lint']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Unit Test
        id: unit-test
        run: |
          yarn install
          yarn test
      - name: Upload unit coverage output
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_coverage
          path: |
            coverage/test-report.xml
            coverage/lcov.info
      # - name: Slack Failed Notification
      #   uses: someimportantcompany/github-actions-slack-message@v1
      #   if: failure()
      #   with:
      #     webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     channel: ${{ env.SLACK_CHANNEL }}
      #     text: "[QA] GitHub Action: Build failed in step ${{github.job}}"
      #     color: failure

  # sonarqube_scan:
  #   runs-on: ubuntu-latest
  #   needs: ['unit_test']
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.4.0
  #       with:
  #         fetch-depth: 0
  #     - name: Download unit coverage output
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: unit_test_coverage
  #         path: coverage
  #     - uses: sonarsource/sonarqube-scan-action@v1.1.0
  #       with:
  #         args: >
  #           -Dsonar.verbose=true
  #           -Dsonar.qualitygate.wait=true
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # docker_build_test:
  #   runs-on: ubuntu-latest
  #   needs: ['sonarqube_scan']
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.4.0
  #       with:
  #         fetch-depth: 0
  #     - name: Get hash commit
  #       id: hash_commit
  #       shell: bash
  #       run: |
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #     - name: Container Registry Login
  #       uses: azure/docker-login@v1
  #       with:
  #         login-server: acryprojecteastus${{ secrets.ENVIRONMENT }}.azurecr.io
  #         username: ${{ secrets.AZURE_ACR_USERNAME_DEV }}
  #         password: ${{ secrets.AZURE_ACR_PASSWORD_DEV }}
  #     - name: Container Build and Push (DryRun)
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         tags: "acryprojecteastus${{ secrets.ENVIRONMENT }}.azurecr.io/${{ github.event.repository.name }}-${{ secrets.ENVIRONMENT }}:${{ steps.hash_commit.outputs.sha_short }}"  # yamllint disable-line rule:line-length
  #         push: false
